### ISSUE TITLE
freetype in PR #17 was not configured correctly

### ISSUE THREAD

**Issue by FTPiano** [pspdev/psp-ports#21]
Ah ha, here is the "someone" in PR #17 :-p. Unfortunately, this commit really gives me some trouble on Mac OS X:

- Executable names like "psp-gcc.exe" & "psp-ar.exe" will not work in non-emulated POSIX environments, e.g., OS X in my case, due to the ".exe" suffix. However, this may not be a big deal, they could be easily detected & fixed.
- There is no target named "install" in the make system, which means...well, breaks the outer build script in psplibraries/script/freetype.sh. Even a quick fix like this will **not** work:

 ```diff
 --- a/scripts/freetype.sh
 +++ b/scripts/freetype.sh
 @@ -1,3 +1,2 @@
  get_pspports freetype
 -run_autogen_build
 -
 +run_make -j `num_cpus`
 ```

 As a result, the library could not install itself properly. There will be no header files nor library files in usual places such as "/usr/local/pspdev/psp/include" & "/usr/local/pspdev/psp/lib", not even a "freetype-config" script to figure out where the files resides in, and what options & flags should be passed to compiler, this is really **awkward**...especially when composing Makefiles.

So...@gtzampanakis could you please fix these issues and make the library fit into the whole collection gracefully? Thanks in advance.

**Comment by artart78** [comment]
Err, sorry for merging something which has trivial issues like this... @gtzampanakis, can you fix it? What did you change in ps2sdk-ports? I don't think ps2sdk-ports build only for MinGW.
Otherwise I'll revert it and re-merge #19.

**Comment by gtzampanakis** [comment]
I will have a look and try to fix this.

However, if the merge is reverted then the it will revert to a state where it doesn't build on MinGW.

**Comment by gtzampanakis** [comment]
Just submitted the harmless PR #22 which fixes the "exe" suffix issue.
Regarding the issue with the external script that breaks, this script (psplibraries/script/freetype.sh) is in another repo. @FTPiano , can you please list the process that PR #17 breaks? I assume it is a process that installs a working environment for PSP development.

**Comment by FTPiano** [comment]
Environment setup was completed by yet another repo "psptoolchain", IMHO. However, "psplibraries" provides valuable software resources for homebrew development on PSP.

Previously, I could almost depoy all libraries in a one-command-line fashion: `./libraries.sh`. But now without a configure script & an "install" target in Makefile, the whole process will end like this:

```
make: *** No rule to make target `install'.  Stop.
Failed installing freetype!
Installation finished.
Failed installing: freetype
```

**Comment by xantares** [comment]
+1 bring back autotools, this breaks freetype.sh from psplibraries

**Comment by artart78** [comment]
Can you try with the file https://raw.githubusercontent.com/ps2dev/ps2sdk-ports/master/freetype-2.4.12/autogen.sh added to the freetype directory? This file comes from the ps2sdk-ports, and has not been added by @gtzampanakis, although it should've been in order for the script to work. (Actually, I trusted the fact that it was portable from the fact that it comes from ps2sdk-ports.)

I don't have much time right now, but if it doesn't work with the file added, I may be able to check it out this weekend.

**Comment by xantares** [comment]
no:
```
You must be in the same directory as `autogen.sh'.
Bootstrapping doesn't work if srcdir != builddir.
```

**Comment by artart78** [comment]
And if you also add the builds/unix subdirectory? (As it can be found in https://github.com/ps2dev/ps2sdk-ports/ )

**Comment by davidgfnet** [comment]
Yeah having the same issue. @gtzampanakis could you fix (/revert) this? I think not having "freetype-config" is not a good practice.

**Comment by gtzampanakis** [comment]
Just created #24 which reverts my changes for which people complained.

**Comment by gtzampanakis** [comment]
Just created #24 which reverts my changes for which people complained.
