### ISSUE TITLE
libzzip installation adds broken links with useless names

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-ports#28]
This part can probably be removed all together: https://github.com/pspdev/psp-ports/blob/b9923543b1c0ef280d8cc6d7bbaf16c5eaedd507/zziplib/zzip/Makefile.am#L84-L94

Here is a picture of the result:
![Screenshot from 2020-05-01 22-21-39](https://user-images.githubusercontent.com/5042659/80838827-2cec7400-8bfa-11ea-9598-a92bed9007cd.png)

I can make a pull request, but it would be untested.

**Comment by dbeef** [comment]
Good finding.

Runtime libraries are not needed at all (PSP platform constraints) and can be removed.
However, some testing is needed to make sure that it does not break any existing build.
